### ISSUE TITLE
Segfault at startup

### ISSUE THREAD

**Issue by osa1** [das-labor/panopticon#64] opened 2015-07-03 23:22 UTC
I just built it from source on a 64bit Linux system, but I can't run it because it's failing with segfault on startup. This is the stack trace.

```
(gdb) bt
#0  0x00007f94a1f4e792 in QShortcutMap::addShortcut(QObject*, QKeySequence const&, Qt::ShortcutContext, bool (*)(QObject*, Qt::ShortcutContext)) () at /usr/lib64/libQt5Gui.so.5
#1  0x00007f948dfaa1df in  () at /usr/lib64/qt5/qml/QtQuick/Controls/libqtquickcontrolsplugin.so
#2  0x00007f948dfc1ca5 in  () at /usr/lib64/qt5/qml/QtQuick/Controls/libqtquickcontrolsplugin.so
#3  0x00007f94a3e5210a in  () at /usr/lib64/libQt5Qml.so.5
#4  0x00007f94a3e54f94 in  () at /usr/lib64/libQt5Qml.so.5
#5  0x00007f94a3e56596 in  () at /usr/lib64/libQt5Qml.so.5
#6  0x00007f94a3e52fad in  () at /usr/lib64/libQt5Qml.so.5
#7  0x00007f94a3e539c3 in  () at /usr/lib64/libQt5Qml.so.5
#8  0x00007f94a3e5587d in  () at /usr/lib64/libQt5Qml.so.5
#9  0x00007f94a3e56596 in  () at /usr/lib64/libQt5Qml.so.5
#10 0x00007f94a3e52fad in  () at /usr/lib64/libQt5Qml.so.5
#11 0x00007f94a3e539c3 in  () at /usr/lib64/libQt5Qml.so.5
#12 0x00007f94a3e5587d in  () at /usr/lib64/libQt5Qml.so.5
#13 0x00007f94a3e56596 in  () at /usr/lib64/libQt5Qml.so.5
#14 0x00007f94a3e52fad in  () at /usr/lib64/libQt5Qml.so.5
#15 0x00007f94a3e539c3 in  () at /usr/lib64/libQt5Qml.so.5
#16 0x00007f94a3e5587d in  () at /usr/lib64/libQt5Qml.so.5
#17 0x00007f94a3e56596 in  () at /usr/lib64/libQt5Qml.so.5
#18 0x00007f94a3e52fad in  () at /usr/lib64/libQt5Qml.so.5
#19 0x00007f94a3e539c3 in  () at /usr/lib64/libQt5Qml.so.5
#20 0x00007f94a3e5587d in  () at /usr/lib64/libQt5Qml.so.5
#21 0x00007f94a3e56596 in  () at /usr/lib64/libQt5Qml.so.5
#22 0x00007f94a3e52fad in  () at /usr/lib64/libQt5Qml.so.5
#23 0x00007f94a3e539c3 in  () at /usr/lib64/libQt5Qml.so.5
#24 0x00007f94a3e54814 in  () at /usr/lib64/libQt5Qml.so.5
#25 0x00007f94a3de0ce2 in QQmlComponentPrivate::beginCreate(QQmlContextData*) () at /usr/lib64/libQt5Qml.so.5
#26 0x00007f94a3ddecbf in QQmlComponent::create(QQmlContext*) () at /usr/lib64/libQt5Qml.so.5
#27 0x00007f94a3e49927 in QQmlApplicationEnginePrivate::_q_finishLoad(QObject*) () at /usr/lib64/libQt5Qml.so.5
#28 0x00007f94a3e4a3b2 in QQmlApplicationEnginePrivate::startLoad(QUrl const&, QByteArray const&, bool) () at /usr/lib64/libQt5Qml.so.5
#29 0x00007f94a3e4a3ed in QQmlApplicationEngine::load(QUrl const&) () at /usr/lib64/libQt5Qml.so.5
#30 0x0000000000466c11 in main ()
```

I can provide more info if needed or upload the core dump to some place.

**Comment by flanfly** [comment] 2015-07-03 23:30
Well. I can't say much about a 30 frame deep backtrace into some Qt library. What's your distribution?

**Comment by osa1** [comment] 2015-07-04 00:20
I thought this may be because of a bug in how Qt related things initialized in Panopticon.. This is from openSUSE 13.2.

**Comment by flanfly** [comment] 2015-07-06 12:59
I'll try to reproduce it in a OpenSuSE VM. I'm in the process of rewriting Panopticon in Rust, so this problem may be fixed in the next version.

**Comment by flanfly** [comment] 2015-08-23 20:16
Can't reproduce. Reopen if the problem persists.

**Closed by flanfly** 2015-08-23 20:16 UTC
Labels: bug, lib
